#!/usr/bin/env node
// Injects ui/index.html into src/worker.js -> dist/worker.js
//
// The Worker serves its UI from a single script (no static-assets binding), so the
// HTML must be embedded. Keeping it in ui/index.html means editors/linters see real
// HTML instead of a 1200-line template literal.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const [worker, html] = await Promise.all([
  readFile(join(root, 'src/worker.js'), 'utf8'),
  readFile(join(root, 'ui/index.html'), 'utf8'),
]);

if (!worker.includes('UI_HTML')) {
  throw new Error('src/worker.js has no UI_HTML placeholder — build would silently drop the UI');
}

// Strip the test-only export block so it never ships to the edge.
const testMarker = '// Exported for unit tests; not part of the HTTP surface.';
const workerBody = worker.includes(testMarker) ? worker.slice(0, worker.indexOf(testMarker)).trimEnd() : worker;

if (!/export default workers_default;/.test(workerBody)) {
  throw new Error('src/worker.js is missing its default export — the Worker would have no fetch handler');
}

// Escape the three sequences that would break out of a template literal.
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const out = `// GENERATED by scripts/build.mjs — edit src/worker.js or ui/index.html instead.
const UI_HTML = \`${escaped}\`;

${workerBody}
`;

await mkdir(join(root, 'dist'), { recursive: true });
await writeFile(join(root, 'dist/worker.js'), out);

console.log(`built dist/worker.js — ${out.length} bytes (ui: ${html.length}, worker: ${worker.length})`);
